# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - apt-get update && apt-get install --yes zip
          - npm install
          #- npm run build
          #- npm test
          - zip -r application.zip .
          - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.3
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'us-west-1'
              APPLICATION_NAME: 'node-express'
              COMMAND: 'upload-only'
              ZIP_FILE: 'application.zip'
              # S3_BUCKET: 'elasticbeanstalk-ap-southeast-2-542238120592'
              VERSION_LABEL: 'deploy-$BITBUCKET_BUILD_NUMBER-multiple'
    - step:
        name: "Deploy to Staging"
        deployment: staging
        script:
          - echo "Deploying to staging..."
          - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.3
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'us-west-1'
              APPLICATION_NAME: 'node-express'
              COMMAND: 'deploy-only'
              VERSION_LABEL: 'deploy-$BITBUCKET_BUILD_NUMBER-multiple'
              ENVIRONMENT_NAME: 'staging'
              WAIT: 'true'
    - step:
        name: "Deploy to Production"
        deployment: production
        trigger: manual
        script:
          - echo "Deploying to production..."
          - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.3
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'us-west-1'
              APPLICATION_NAME: 'node-express'
              COMMAND: 'deploy-only'
              VERSION_LABEL: 'deploy-$BITBUCKET_BUILD_NUMBER-multiple'
              ENVIRONMENT_NAME: 'production'
              WAIT: 'true'
